apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-bot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:moszie248/argo-app.git
    targetRevision: main
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true